package:
  name: mplwidget
  version: 0.1.0

source:
  git_url: https://github.com/cstrandhagen/mplwidget.git

build:
  number: 0
  #preserve_egg_dir: True

requirements:
  build:
    - python
    - matplotlib
    - lmfit
    - numpy
    - scipy

  run:
    - python
    - matplotlib
    - lmfit
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - mplwidget

about:
  home: https://github.com/cstrandhagen/mplwidget
  license: MIT
summary: enhanced matplotlib widget for QT